apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: alyaabadr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: alyaabadr/my-app:v1
        ports:
        - containerPort: 8091
