apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  namespace: alyaabadr
spec:
  selector:
    app: my-app
    
  ports:
    - protocol: TCP
      port: 8091
      targetPort: 8091
      
  type: NodePort    

