// Load shared libraries
@Library('my-shared-library') _

pipeline {
    agent any

    environment {
        openshiftClusterURL  = 'https://api.ocp-training.ivolve-test.com:6443'
        K8S_NAMESPACE =        'alyaabadr'
        imageName   		   = 'alyaabadr/my-app'
        OPENSHIFT_CREDENTIALS = 'openshift-jenkins-token'
        dockerhub-credentials-id	    = 'DockerHub'
        openshiftCredentialsID =  'openshift-jenkins--token'
        APP_NAME = 'my-app'
    }

    stages {
      
      stage('Build Docker Image') {
            steps {
                script {
                    buildDockerImage(env.DOCKER_IMAGE, env.DOCKER_TAG)
                }
            }
        }
        
        stage('Push Docker Image') {
            steps {
                script {
                    pushDockerImage(env.DOCKER_IMAGE, env.DOCKER_TAG, 'dockerhub-credentials-id')
                }
            }
        }
        
        stage('Update Kubernetes Deployment') {
            steps {
                script {
                    updateK8sDeployment(env.DOCKER_IMAGE, env.DOCKER_TAG, 'k8s/deployment.yaml')
                }
            }
        }
        
        stage('Deploy to Kubernetes') {
            steps {
                script {
                    deployToK8s(env.DEPLOYMENT_NAME, env.K8S_NAMESPACE)
                }
            }
        }
        
        stage('Deploy Kubernetes Service') {
            steps {
                script {
                    deployK8sService(env.SERVICE_NAME, env.K8S_NAMESPACE)
                }
            }
        }
    }

    post {
        always {
            echo 'This will always run'
        }
        success {
            echo 'This will run only if the pipeline succeeds'
        }
        failure {
            echo 'This will run only if the pipeline fails'
        }
    }
}


