// Load shared libraries
@Library('my-shared-library') _

pipeline {
    agent any

    environment {
        openshiftProject 	    = 'alyaabadr'
        K8S_NAMESPACE =        'alyaabadr'
        imageName   		   = 'alyaabadr/my-app'
        openshiftClusterURL	    = 'https://api.ocp-training.ivolve-test.com:6443'
        dockerHubCredentialsID	    = 'DockerHub'
        openshiftCredentialsID =  'openshift-jenkins--token'
        APP_NAME = 'my-app'
    }

    stages {
      
      stage('Build Docker Image') {
            steps {
                script {
                    buildDockerImage(env.DOCKER_IMAGE, env.DOCKER_TAG)
                }
            }
        }
        
        stage('Push Docker Image') {
            steps {
                script {

	  withCredentials([usernamePassword(credentialsId: "${dockerhub-credentials}", usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) 
 {
		sh "docker login -u ${USERNAME} -p ${PASSWORD}"
}
                    

          
                    pushDockerImage(env.DOCKER_IMAGE, env.DOCKER_TAG, 'dockerHubCredentialsID')
                }
            }
        }
        
      
        
        stage('Deploy to Kubernetes') {
             steps {
                script { 
                	dir('openShift') {
				deployOnOpenShift("${openshiftCredentialsID}", "${openshiftClusterURL}", "${openshiftProject}", "${imageName}")
                    	}
                }
            }
        }
        
       
    }

    post {
        always {
            echo 'This will always run'
        }
        success {
            echo 'This will run only if the pipeline succeeds'
        }
        failure {
            echo 'This will run only if the pipeline fails'
        }
    }
}


